apiVersion: v1
description: GitLab Auto-deploy Helm Chart - Octoshell (rails+pg+redis+sidekiq)
name: octoshell
version: 0.0.1
icon: https://gitlab.com/gitlab-com/gitlab-artwork/raw/master/logo/logo-square.png
