dependencies:
  - name: postgresql
    version: "13.3.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "6.2.4"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
